server:
  port: 6001
spring:
  application:
    name: hicloud-commonservice-gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      
      discovery:
        enabled: true
        instanceId: hicloud-commonservice-gateway1
        serviceName: hicloud-commonservice-gateway
        hostname: 127.0.0.1
        port: 6001
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        tags: dev
    gateway: # spring cloud gateway 路由配置方式
      discovery: #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator: #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
      - id: hicloud-demo   #网关路由到demo服务hicloud-demo
        uri: lb://hicloud-demo
        predicates:
        - Path=/hicloud-demo/**
        filters:
        - StripPrefix= 1
      - id: hicloud-test   #网关路由到test服务hicloud-test
        uri: lb://hicloud-test
        predicates:
        - Path=/hicloud-test/**
        filters:
        - StripPrefix= 1

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

feign:
  hystrix:
    enabled: true
